// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimulacroPrueba.Data;

#nullable disable

namespace SimulacroPrueba.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251010134055_InicialSimulacro")]
    partial class InicialSimulacro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PasajerosReservasVuelos", b =>
                {
                    b.Property<int>("pasajerosId")
                        .HasColumnType("int");

                    b.Property<int>("reservasVuelosId")
                        .HasColumnType("int");

                    b.HasKey("pasajerosId", "reservasVuelosId");

                    b.HasIndex("reservasVuelosId");

                    b.ToTable("PasajerosReservasVuelos");
                });

            modelBuilder.Entity("SimulacroPrueba.Models.GestionVuelos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Llegada")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Salida")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SillasDisponible")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GestionVuelos");
                });

            modelBuilder.Entity("SimulacroPrueba.Models.Pasajeros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pasajeros");
                });

            modelBuilder.Entity("SimulacroPrueba.Models.ReservasVuelos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AsientoAsignado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoVuelo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoVuelov")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha_Hora")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GestionVuelosId")
                        .HasColumnType("int");

                    b.Property<string>("NombrePasajero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Origen_Destino")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GestionVuelosId");

                    b.ToTable("ReservasVuelos");
                });

            modelBuilder.Entity("PasajerosReservasVuelos", b =>
                {
                    b.HasOne("SimulacroPrueba.Models.Pasajeros", null)
                        .WithMany()
                        .HasForeignKey("pasajerosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimulacroPrueba.Models.ReservasVuelos", null)
                        .WithMany()
                        .HasForeignKey("reservasVuelosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimulacroPrueba.Models.ReservasVuelos", b =>
                {
                    b.HasOne("SimulacroPrueba.Models.GestionVuelos", null)
                        .WithMany("reservasVuelos")
                        .HasForeignKey("GestionVuelosId");
                });

            modelBuilder.Entity("SimulacroPrueba.Models.GestionVuelos", b =>
                {
                    b.Navigation("reservasVuelos");
                });
#pragma warning restore 612, 618
        }
    }
}
